<form id="<?php echo $this->id; ?>" action="<?php echo $this->action; ?>" method="<?php echo $this->method; ?>" class="form-horizontal">
    <fieldset>
        <legend><?php echo $this->title; ?></legend>
        <?php foreach($this->fields as $fieldName => $field): ?>
        <div class="control-group">
            <?php if(isset($field['label']) && $field['label']): ?>
            <label class="control-label" for="<?php echo $fieldName; ?>">
                <?php echo $field['label']; ?>
            </label>
            <?php endif; ?>
            <div class="controls">
                <?php echo $field['html']; ?>
            </div>
        </div>
        <?php endforeach; ?>
        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn"><?php echo $this->submitText; ?></button>
            </div>
        </div>
    </fieldset>
</form>